---

- name: deploy container to docker host
  hosts: appserver
  gather_facts: false
  become: true
  remote_user: ec2-user
  tasks:

  - name: deploy app to container
    docker_container:
         name: webapp
         image: ganeshhp/tomcatapp:1.0
         state: started
         restart: yes
         ports:
            - "8081:8080"

